### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by strawberry-code** [pjhades/bash-snake#2] opened 2017-11-22 14:28 UTC
Nice work! But not working on macOS Terminal App based con Bash shell unicode UTF-8.

The script starts and then I see scrolling many characters; after some seconds it stops.

This is what I see at the begin:
<img width="1680" alt="schermata 2017-11-22 alle 15 25 24" src="https://user-images.githubusercontent.com/18684103/33132279-8f6b691c-cf99-11e7-93b0-dafec15c4106.png">

and this at the end:
<img width="1680" alt="schermata 2017-11-22 alle 15 24 49" src="https://user-images.githubusercontent.com/18684103/33132276-8f1d21d0-cf99-11e7-85ac-949881f26047.png">

**Comment by pjhades** [comment] 2018-01-21 22:04
Hi! Sorry for the late response. It seems like the issue is caused by the escape sequences and signals. I didn't dig into the reason but I **guess** that newer versions of bash does not recognize some escape sequence format any more.

Regarding the signals, I was using the real-time signals for IPC but that seem only work on Linux. (This was written long ago when I didn't have OS X to test it).

So please check out the new master branch. (I did some rebasing so there's no PR for this sorry) Thanks for opening this. I close this for now and feel free to reopen it if the issue still troubles you.

**Closed as completed** 2018-01-21 22:05 UTC
Labels: bug
